import {initial,step,nodes,endings,currentEnding,mood,validate,type State} from './game';
const $=(id:string)=>document.getElementById(id)!;
let state:State=initial(), started=false, busy=false, db:IDBDatabase|null=null, saved=false;
let storageError='', modalFocus:HTMLElement|null=null;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function openDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('le-garde-du-pont-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('progress');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Fermez les autres onglets du jeu, puis réessayez.'));});}
async function read(){return new Promise<unknown>((resolve,reject)=>{if(!db)return reject(new Error('Sauvegarde indisponible.'));const t=db.transaction('progress','readonly'),r=t.objectStore('progress').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function write(s:State){return new Promise<void>((resolve,reject)=>{if(!db)return reject(new Error('Le navigateur a bloqué la sauvegarde.'));const t=db.transaction('progress','readwrite');t.objectStore('progress').put(s,'current');t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
async function persist(){saved=false;renderStatus('Sauvegarde en cours…');try{await write(state);saved=true;storageError='';}catch{storageError='Progression non enregistrée. Réessayez ou exportez votre sauvegarde avant de fermer le jeu.';}renderStatus();}
function renderStatus(msg?:string){$('save-status').textContent=msg??(saved?'Progression enregistrée sur cet appareil':storageError?'Non enregistrée':'Aucune partie enregistrée');$('error-box').hidden=!storageError;$('error-text').textContent=storageError;}
function render(){
const end=currentEnding(state);$('intro').hidden=started;$('play').hidden=!started;
$('coins').textContent=String(state.coins);$('cheese').textContent=state.cheese?'1':'0';$('trust').textContent=String(state.trust);$('patience').textContent=String(3-state.anger);
$('mood').textContent=mood(state);$('scene').setAttribute('data-mood',mood(state));$('discovered').textContent=`${state.endings.length} / 5`;
$('ending-list').innerHTML=state.endings.length?state.endings.map(e=>`<li><span>${endings[e].symbol}</span> ${escape(endings[e].title)}</li>`).join(''):'<li class="empty">Aucune fin découverte. Votre histoire commence au pont.</li>';
$('journal').innerHTML=state.history.length?state.history.map((s,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${escape(s)}</li>`).join(''):'<li class="empty">Votre premier choix attend d’être écrit.</li>';
if(started){$('chapter').textContent=end?'L’épilogue':nodes[state.node].chapter;$('dialogue').textContent=end?endings[end].title:nodes[state.node].text;$('aside').textContent=end?endings[end].description:nodes[state.node].aside;$('speaker').textContent=end?(end==='banned'||end==='fled'?'LE DÉTOUR':'LE PASSAGE'):'BRÖM, LE GARDE DU PONT';$('dialogue').classList.toggle('ending-title',!!end);$('choices').innerHTML='';
if(end){$('result').hidden=false;$('result').textContent=(end==='fled'||end==='banned'?'Fin découverte':'Passage obtenu')+' · '+state.endings.length+' sur 5';const b=document.createElement('button');b.className='primary replay';b.textContent='Tenter une autre histoire';b.onclick=()=>restart();$('choices').append(b);}else{$('result').hidden=true;nodes[state.node].choices.forEach((c,i)=>{const disabled=!!(c.needsCheese&&!state.cheese)||!!(c.cost&&state.coins<c.cost);const b=document.createElement('button');b.className='choice';b.disabled=disabled||busy;b.innerHTML=`<span class="choice-index">${String(i+1).padStart(2,'0')}</span><span><strong>${escape(c.label)}</strong><small>${disabled?'Ressource indisponible':escape(c.hint)}</small></span><span class="choice-mark">✦</span>`;b.onclick=()=>choose(c.id);$('choices').append(b);});}}
($('export') as HTMLButtonElement).disabled=!started;renderStatus();
}
async function choose(id:string){if(busy||!started)throw new Error('La partie n’est pas prête.');busy=true;try{state=step(state,id);saved=false;render();await persist();}catch(e){storageError=(e as Error).message;renderStatus();}finally{busy=false;render();$('dialogue').focus();}return {node:state.node,ending:currentEnding(state),saved};}
async function restart(){state=initial(state.endings);started=true;saved=false;render();await persist();$('dialogue').focus();}
function showDialog(id:string){modalFocus=document.activeElement as HTMLElement;($ (id) as HTMLDialogElement).showModal();}
$('start').onclick=async()=>{started=true;render();await persist();$('dialogue').focus();};
$('rules').onclick=()=>showDialog('rules-dialog');$('collection').onclick=()=>showDialog('collection-dialog');$('journal-button').onclick=()=>showDialog('journal-dialog');$('restart').onclick=()=>showDialog('restart-dialog');$('restart-confirm').onclick=()=>{($('restart-dialog')as HTMLDialogElement).close();void restart();};
document.querySelectorAll<HTMLDialogElement>('dialog').forEach(d=>{d.querySelectorAll<HTMLButtonElement>('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>modalFocus?.focus());});
$('retry').onclick=async()=>{if(busy)return;busy=true;try{db??=await openDB();if(started)await persist();else{const loaded=await read();if(loaded){state=validate(loaded);started=true;saved=true;}storageError='';render();}}catch{storageError='Sauvegarde toujours indisponible. Exportez votre partie ou jouez sans enregistrement.';renderStatus();}finally{busy=false;}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='le-garde-du-pont-sauvegarde.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onclick=()=>($('import-file')as HTMLInputElement).click();
$('import-file').onchange=async(e)=>{const input=e.target as HTMLInputElement;const f=input.files?.[0];if(!f)return;try{if(f.size>50000)throw new Error('Fichier trop volumineux. Choisissez une sauvegarde JSON du jeu.');const loaded=validate(JSON.parse(await f.text()));state=loaded;started=true;render();await persist();}catch{storageError='Import impossible : le fichier doit être une sauvegarde JSON valide du jeu. Votre partie actuelle est conservée.';renderStatus();}input.value='';};
$('scene-image').onerror=()=>{$('image-error').hidden=false;};
async function init(){try{db=await openDB();const stored=await read();if(stored){state=validate(stored);started=true;saved=true;}}catch{storageError='Sauvegarde indisponible ou incompatible. Vous pouvez jouer sans enregistrement et exporter votre partie.';}render();$('loading').hidden=true;($('start') as HTMLButtonElement).disabled=false;}
void init();
// Browser-agent support uses exactly the same journey as visible controls.
const mc=(document as Document&{modelContext?:{registerTool:(t:unknown,o?:unknown)=>void}}).modelContext;
if(mc){const lifecycle=new AbortController();try{mc.registerTool({name:'read_bridge_game',description:'Lire la partie et ses choix disponibles.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,started,saved,choices:nodes[state.node]?.choices.map(c=>({id:c.id,label:c.label}))??[]})},{signal:lifecycle.signal});mc.registerTool({name:'choose_bridge_reply',description:'Choisir une réponse dans la négociation commencée et enregistrer son résultat.',inputSchema:{type:'object',properties:{choiceId:{type:'string'}},required:['choiceId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(v:unknown)=>{const id=(v as {choiceId?:unknown})?.choiceId;if(typeof id!=='string'||!nodes[state.node]?.choices.some(c=>c.id===id))throw new Error('Choix invalide.');return choose(id);}},{signal:lifecycle.signal});window.addEventListener('pagehide',()=>lifecycle.abort());}catch{/* Optional browser API absent or unavailable. */}}
